---
title: "Cleaned"
author: "XP"
date: "5/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

#Cleaning Part 1

```{r}
#Load all training data
train = read.csv('Data/training.csv')
head(train)
```

```{r}
droplist = c("PRIMEUNIT", "AUCGUART", "Trim", "VehicleAge", "RefId", "SubModel", "WheelType", "VNZIP1")
cleaned <- train[, !(names(train) %in% droplist)]
head(cleaned)
names(cleaned)

```


```{r}
cleaned$PurchDate <- as.Date(cleaned$PurchDate, format = "%m/%d/%Y")
class(cleaned$PurchDate)
```

```{r}
levels(cleaned$Auction)
```

```{r}
nrow(is.na(cleaned$VehYear))
```


```{r}
levels(cleaned$Make)
cleaned$Make[cleaned$Make=='TOYOTA SCION'] = 'SCION'
table(cleaned$Make)
cleaned$Make <- factor(cleaned$Make)
```

```{r}
length(levels(cleaned$Model))
#table(cleaned$Model)
#a = unique(train$Model)
#a = strsplit(a, '')
#a = unlist(a)
#sort(table(a), decreasing = T)  
```

```{r}
table(cleaned$Color)
nrow(is.na(cleaned$Color))
cleaned[cleaned$Color!="NOT AVAIL",] -> cleaned
cleaned[cleaned$Color!="NULL",] -> cleaned
factor(cleaned$Color) -> cleaned$Color
```

```{r}
#clean transmission data
levels(cleaned$Transmission)
cleaned <- cleaned%>%
  mutate(Transmission = replace(Transmission, Transmission=="Manual", "MANUAL"))
  
cleaned <- cleaned%>%
  filter(Transmission =="MANUAL"| Transmission =="AUTO")

cleaned$Transmission <- factor(cleaned$Transmission)
```

```{r}
table(cleaned$Nationality)
cleaned[cleaned$Nationality!="NULL",] -> cleaned
cleaned$Nationality <- factor(cleaned$Nationality)
```

```{r}
table(cleaned$Size)
cleaned<- cleaned%>%
  filter(Size!="NULL")
cleaned$Size <- factor(cleaned$Size)
```

```{r}
table(cleaned$TopThreeAmericanName)
cleaned$TopThreeAmericanName <- factor(cleaned$TopThreeAmericanName)
```

```{r}
#add premium
names(cleaned)

for (i in 14:21){
  cleaned[,i] <- as.numeric(cleaned[,i])
}

cleaned$CostDiff <-  cleaned$VehBCost - cleaned$MMRAcquisitionAuctionAveragePrice
summary(cleaned$CostDiff)
```

```{r}
#export cleaned data
write.csv(cleaned, file = "Data/cleaned.csv", row.names=FALSE)
```


#Cleaning Part 2

```{r}
read.csv("Data/cleaned.csv") -> cleaned
head(cleaned)
```

```{r}
#Split year, month, day as three features
cleaned$PurchDate <- as.Date(cleaned$PurchDate)
cleaned$PurchYear <- format(cleaned$PurchDate, format = '%Y')
cleaned$PurchMonth <- format(cleaned$PurchDate, format = '%m')
cleaned$PurchDay <- format(cleaned$PurchDate, format = '%d')
cleaned$PurchYear <- as.factor(cleaned$PurchYear)
cleaned$PurchMonth <- as.factor(cleaned$PurchMonth)
cleaned$PurchDay <- as.factor(cleaned$PurchDay)
cleaned[, -2] -> cleaned
head(cleaned)
```

```{r}
#Narrow down model to its first word
firstword <- function (x){
  x <- as.character(x)
  strsplit(x, " ")[[1]][1] -> word
  word
}

cleaned$Model <- sapply(cleaned$Model, firstword)
head(cleaned)
```

```{r}
 table(cleaned$Make)
```

```{r}
#Delete HUMMER and PLYMOUTH since there are only 1 and 2 cars from these two brands.
cleaned[!cleaned$Make %in% c("HUMMER", "PLYMOUTH"),] -> cleaned
table(cleaned$Make)
```

```{r}
#Decrease the category of model from each brand to its top 4 model plus other model.
levels(cleaned$Make) -> makelist
for (mk in makelist){
    table(cleaned$Model[cleaned$Make==mk]) -> modeltable
  modeltable[order(modeltable,decreasing = T)] -> modeltable
  cleaned$Model[cleaned$Make==mk & cleaned$Model==names(modeltable)[1]] <- "MODEL1"
  cleaned$Model[cleaned$Make==mk & cleaned$Model==names(modeltable)[2]] <- "MODEL2"
  cleaned$Model[cleaned$Make==mk & cleaned$Model==names(modeltable)[3]] <- "MODEL3"
  cleaned$Model[cleaned$Make==mk & cleaned$Model==names(modeltable)[4]] <- "MODEL4"
  cleaned$Model[cleaned$Make==mk & !cleaned$Model %in% c("MODEL1", "MODEL2", "MODEL3", "MODEL4")] <- "OTHER"
}
cleaned$Model <- as.factor(cleaned$Model)
table(cleaned$Model)
head(cleaned)
table(cleaned$BYRNO)
```

```{r}
# export cleaned data
write.csv(cleaned, file = "Data/cleaned.csv", row.names=FALSE)
```



#Model: XGBoost

```{r}
# Prepration for Boosting
library(xgboost)
cleaned <- read.csv("Data/cleaned.csv")
names(cleaned)
#Convert categorical information to a numeric matrix format 
c(2:8, 10:12, 21:22, 27:29) -> converting
names(cleaned)[converting]
cleaned$BYRNO <- as.character(cleaned$BYRNO)
cleaned$VehYear <- as.character(cleaned$VehYear)
cleaned$PurchYear <- as.character(cleaned$PurchYear)
cleaned$PurchMonth <- as.character(cleaned$PurchMonth)
cleaned$PurchDay <- as.character(cleaned$PurchDay)
model.matrix(~Auction-1,cleaned) -> Auction
model.matrix(~VehYear-1,cleaned) -> VehYear
model.matrix(~Make-1,cleaned) -> Make
model.matrix(~Model-1,cleaned) -> Model
model.matrix(~Color-1,cleaned) -> Color
model.matrix(~Transmission-1,cleaned) -> Transmission
model.matrix(~WheelTypeID-1,cleaned) -> WheelTypeID
model.matrix(~Nationality-1,cleaned) -> Nationality
model.matrix(~Size-1,cleaned) -> Size
model.matrix(~TopThreeAmericanName-1,cleaned) -> TopThreeAmericanName
model.matrix(~BYRNO-1,cleaned) -> BYRNO
model.matrix(~VNST-1,cleaned) -> VNST
model.matrix(~PurchYear-1,cleaned) -> PurchYear
model.matrix(~PurchMonth-1,cleaned) -> PurchMonth
model.matrix(~PurchDay-1,cleaned) -> PurchDay

data_numeric <- cbind(cleaned[, -converting], Auction, VehYear, Make, Model, Color, Transmission, WheelTypeID, Nationality, Size, TopThreeAmericanName, BYRNO, VNST, PurchYear, PurchMonth, PurchDay)

data_matrix <- data.matrix(data_numeric)

# Get the index for test and train split
set.seed(666)
index <- sample(72872, 50000)
# training data
train_data <- data_matrix[index, -1]
train_label <- data_matrix[index, 1]
# testing data
test_data <- data_matrix[-index, -1]
test_label <- data_matrix[-index, 1]

```

```{r}
# put our testing & training data into two seperates data matrix
dtrain <- xgb.DMatrix(data = train_data, label= train_label)
dtest <- xgb.DMatrix(data = test_data, label= test_label)

# Finding distribution of positive and negative cases
table(train_label) 

# train a model using our training data
boost_model <- xgboost(data = dtrain,
                max.depth = 22,    
                nround = 10, 
                eta = 0.3,
                early_stopping_rounds = 3,
                scale_pos_weight = 43895/6105, 
                objective = "binary:logistic",
                gamma = 12)
```


```{r}
# Testing with AUC
#library(PRROC)
pred <- predict(boost_model, dtest)
ROC_graph <- roc.curve(scores.class0 = pred, weights.class0=test_label,
                       curve=TRUE)
plot(ROC_graph)
err <- mean(as.numeric(pred > 0.88) != test_label)
print(paste("test-error=", err))
table(c(test_label,train_label))
8950/(63922+8950)
```

```{r}

```

